#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# --- 1. Create .env if missing ---
if [ ! -f .env ]; then
    cp .env.example .env
    echo ""
    echo ">>> Created .env from .env.example"
    echo ">>> Edit .env to set ALLOWED_IP, GRAFANA_PASSWORD, etc."
    echo ">>> Then run this script again: bash setup.sh"
    echo ""
    exit 0
fi

source .env

# --- 2. Install & connect Tailscale ---
echo "[1/5] Setting up Tailscale..."
if ! command -v tailscale &>/dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi

if [ -z "${TAILSCALE_AUTHKEY:-}" ]; then
    echo ""
    echo ">>> TAILSCALE_AUTHKEY is not set in .env"
    echo ">>> Generate a reusable auth key: https://login.tailscale.com/admin/settings/keys"
    echo ">>> Add it to .env as TAILSCALE_AUTHKEY=tskey-auth-... then re-run: bash setup.sh"
    echo ""
    exit 1
fi

sudo tailscale up --authkey="$TAILSCALE_AUTHKEY" --hostname="${TAILSCALE_HOSTNAME:-deki-admin-tools}" --accept-dns=false

TS_IP=$(tailscale ip -4)
echo "      Tailscale IP: $TS_IP"

# --- 3. Install nginx if not present ---
if ! command -v nginx &>/dev/null; then
    echo "[2/5] Installing nginx..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq nginx
else
    echo "[2/5] nginx already installed"
fi

# --- 4. Generate and install nginx site config ---
# Bound to the Tailscale interface only (not 0.0.0.0), so these tools are
# unreachable from the public internet regardless of firewall/IP config.
# The allow directive is a defense-in-depth backstop restricting to the
# tailnet's CGNAT range in case the bind address is ever misconfigured.
echo "[3/5] Configuring nginx..."

sudo tee /etc/nginx/sites-enabled/admin-tools > /dev/null << NGINX_EOF
# Auto-generated by deki-admin-tools/setup.sh
server {
    listen $TS_IP:80;
    server_name $TS_IP;

    location /portainer/ {
        allow 100.64.0.0/10;
        deny all;
        proxy_pass http://127.0.0.1:9000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /redis/ {
        allow 100.64.0.0/10;
        deny all;
        proxy_pass http://127.0.0.1:8081/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /prometheus/ {
        allow 100.64.0.0/10;
        deny all;
        proxy_pass http://127.0.0.1:9090/prometheus/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /grafana/ {
        allow 100.64.0.0/10;
        deny all;
        proxy_pass http://127.0.0.1:3333/grafana/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location / {
        return 404;
    }
}
NGINX_EOF

sudo nginx -t
sudo systemctl reload nginx

# --- 5. Start containers ---
echo "[4/5] Starting containers..."
docker compose up -d

echo "[5/5] Done."
echo ""
echo "==========================================="
echo "  Admin tools ready! (Tailscale-only access)"
echo "==========================================="
echo ""
echo "  Portainer:       http://$TS_IP/portainer/"
echo "  Redis Commander: http://$TS_IP/redis/"
echo "  Prometheus:      http://$TS_IP/prometheus/"
echo "  Grafana:         http://$TS_IP/grafana/"
echo ""
echo "  Join this tailnet from your own device, then use the URLs above."
echo "  Grafana login:   $GRAFANA_USER / (see .env)"
echo ""
