#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# --- 1. Create .env if missing ---
if [ ! -f .env ]; then
    cp .env.example .env
    echo ""
    echo ">>> Created .env from .env.example"
    echo ">>> Edit .env to set ALLOWED_IP, GRAFANA_PASSWORD, etc."
    echo ">>> Then run this script again: bash setup.sh"
    echo ""
    exit 0
fi

source .env

# --- 2. Detect server IP ---
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "[1/4] Server IP: $SERVER_IP"

# --- 3. Install nginx if not present ---
if ! command -v nginx &>/dev/null; then
    echo "[2/4] Installing nginx..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq nginx
else
    echo "[2/4] nginx already installed"
fi

# --- 4. Generate and install nginx site config ---
echo "[3/4] Configuring nginx..."

ALLOWED_IP="${ALLOWED_IP:-127.0.0.1}"

sudo tee /etc/nginx/sites-enabled/admin-tools > /dev/null << NGINX_EOF
# Auto-generated by deki-admin-tools/setup.sh
server {
    listen 80;
    server_name $SERVER_IP;

    location /portainer/ {
        allow $ALLOWED_IP;
        deny all;
        proxy_pass http://127.0.0.1:9000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /redis/ {
        allow $ALLOWED_IP;
        deny all;
        proxy_pass http://127.0.0.1:8081/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /prometheus/ {
        allow $ALLOWED_IP;
        deny all;
        proxy_pass http://127.0.0.1:9090/prometheus/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /grafana/ {
        allow $ALLOWED_IP;
        deny all;
        proxy_pass http://127.0.0.1:3333/grafana/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location / {
        return 404;
    }
}
NGINX_EOF

sudo nginx -t
sudo systemctl reload nginx

# --- 5. Start containers ---
echo "[4/4] Starting containers..."
docker compose up -d

echo ""
echo "==========================================="
echo "  Admin tools ready!"
echo "==========================================="
echo ""
echo "  Portainer:       http://$SERVER_IP/portainer/"
echo "  Redis Commander: http://$SERVER_IP/redis/"
echo "  Prometheus:      http://$SERVER_IP/prometheus/"
echo "  Grafana:         http://$SERVER_IP/grafana/"
echo ""
echo "  Allowed IP:      $ALLOWED_IP"
echo "  Grafana login:   $GRAFANA_USER / (see .env)"
echo ""
